spring:
  #数据库连接配置
  datasource:
    #连接地址及数据库
    url: jdbc:mysql://118.24.42.127:3306/hide_blog?useUnicode=true&characterEncoding=utf-8
    #用户名
    username: web
    #密码
    password: 960829

  #redis连接配置
  redis:
    # Redis服务器地址
    host: 118.24.42.127
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码
    password: admin123
    # 连接超时时间（毫秒）
    timeout: 0