server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 10001
spring:
  profiles:
    active: prod,service
  thymeleaf:
      #È¡Ïû»º´æ
    cache: false
    mode: LEGACYHTML5